/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'name' : string,
  'typeId' : bigint,
  'description' : string,
  'earnedAt' : Timestamp,
}
export interface DailyMysteryItemData {
  'id' : string,
  'userId' : UserId,
  'lastDailyItemClaim' : [] | [Timestamp],
  'newDailyItemResult' : [] | [MysteryItem],
  'dailyItemBoxOpened' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface FeedItem {
  'status' : Status,
  'username' : string,
  'userId' : UserId,
  'timestamp' : Timestamp,
}
export interface MusicUpload {
  'id' : string,
  'title' : string,
  'file' : ExternalBlob,
  'genre' : string,
  'artist' : string,
  'uploadTime' : Timestamp,
  'uploadedBy' : UserId,
}
export interface MysteryItem {
  'id' : string,
  'visualUrl' : [] | [string],
  'name' : string,
  'description' : string,
  'rewardCooldown' : [] | [bigint],
  'itemType' : MysteryItemType,
  'pointsReward' : [] | [bigint],
}
export type MysteryItemType = { 'message' : null } |
  { 'badge' : null } |
  { 'visual' : null } |
  { 'points' : null };
export type Points = bigint;
export interface PointsStoreItem {
  'id' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'price' : bigint,
}
export interface PointsTransaction {
  'id' : string,
  'transactionType' : TransactionType,
  'userId' : UserId,
  'description' : string,
  'timestamp' : Timestamp,
  'amount' : bigint,
}
export interface SearchResult {
  'bio' : string,
  'username' : string,
  'userId' : UserId,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'profilePicture' : { 'url' : string, 'contentType' : string },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Status = string;
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export type TransactionType = { 'earn' : null } |
  { 'spend' : null } |
  { 'purchase' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'status' : Status,
  'username' : string,
  'createdAt' : Timestamp,
  'badges' : Array<Badge>,
  'publishedAppsCount' : bigint,
  'premiumExpiresAt' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'rewardsClaimed' : bigint,
  'freeTrialStartTime' : [] | [Timestamp],
  'freeTrialExpiresAt' : [] | [Timestamp],
  'lastDailyRewardClaim' : [] | [Timestamp],
  'dailyLoginStreak' : bigint,
  'lastOnline' : Timestamp,
  'followers' : Array<UserId>,
  'following' : Array<UserId>,
  'profilePicture' : { 'url' : string, 'contentType' : string },
  'isPremiumMember' : boolean,
  'points' : Points,
  'musicUploads' : Array<MusicUpload>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateFreeTrial' : ActorMethod<[], undefined>,
  'addMysteryItem' : ActorMethod<[MysteryItem], undefined>,
  'addStoreItem' : ActorMethod<[PointsStoreItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkPointsEligibility' : ActorMethod<[bigint], string>,
  'claimDailyItemsSecret' : ActorMethod<[], [] | [MysteryItem]>,
  'claimDailyReward' : ActorMethod<[], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProfile' : ActorMethod<[string, string], undefined>,
  'deleteMysteryItem' : ActorMethod<[string], undefined>,
  'deleteStoreItem' : ActorMethod<[string], undefined>,
  'getAllMysteryItems' : ActorMethod<[], Array<MysteryItem>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendsMusicUploads' : ActorMethod<[UserId], Array<MusicUpload>>,
  'getLastClaimedMysteryItem' : ActorMethod<[UserId], [] | [MysteryItem]>,
  'getLastOnline' : ActorMethod<[UserId], Timestamp>,
  'getLastOnlineForMultipleUsers' : ActorMethod<
    [Array<UserId>],
    Array<[UserId, Timestamp]>
  >,
  'getPointsBalance' : ActorMethod<[], bigint>,
  'getPointsHistory' : ActorMethod<[], Array<PointsTransaction>>,
  'getProfile' : ActorMethod<[UserId], UserProfile>,
  'getRecentStatuses' : ActorMethod<[bigint], Array<FeedItem>>,
  'getStoreItems' : ActorMethod<[], Array<PointsStoreItem>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserMysteryItems' : ActorMethod<[UserId], Array<DailyMysteryItemData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMysteryItemClaimAvailable' : ActorMethod<[UserId], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'purchasePoints' : ActorMethod<[bigint], string>,
  'purchaseStoreItem' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProfiles' : ActorMethod<[string], Array<SearchResult>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'spendPoints' : ActorMethod<[bigint], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLastOnline' : ActorMethod<[], undefined>,
  'updateMysteryItem' : ActorMethod<
    [string, string, string, [] | [bigint], [] | [string], [] | [bigint]],
    undefined
  >,
  'updateProfile' : ActorMethod<
    [string, { 'url' : string, 'contentType' : string }],
    undefined
  >,
  'updateStoreItem' : ActorMethod<[string, string, string, bigint], undefined>,
  'upgradeToPremium' : ActorMethod<[bigint], undefined>,
  'uploadMusic' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];