/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GroupId = IDL.Text;
export const UserId = IDL.Principal;
export const MysteryItemType = IDL.Variant({
  'message' : IDL.Null,
  'badge' : IDL.Null,
  'visual' : IDL.Null,
  'points' : IDL.Null,
});
export const MysteryItem = IDL.Record({
  'id' : IDL.Text,
  'visualUrl' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rewardCooldown' : IDL.Opt(IDL.Nat),
  'itemType' : MysteryItemType,
  'pointsReward' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const PointsStoreItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Status = IDL.Text;
export const Badge = IDL.Record({
  'name' : IDL.Text,
  'typeId' : IDL.Nat,
  'description' : IDL.Text,
  'earnedAt' : Timestamp,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MusicUpload = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
  'uploadTime' : Timestamp,
  'uploadedBy' : UserId,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'status' : Status,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'badges' : IDL.Vec(Badge),
  'publishedAppsCount' : IDL.Nat,
  'premiumExpiresAt' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'rewardsClaimed' : IDL.Nat,
  'freeTrialStartTime' : IDL.Opt(Timestamp),
  'freeTrialExpiresAt' : IDL.Opt(Timestamp),
  'lastDailyRewardClaim' : IDL.Opt(Timestamp),
  'dailyLoginStreak' : IDL.Nat,
  'lastOnline' : Timestamp,
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'profilePicture' : IDL.Record({ 'url' : IDL.Text, 'contentType' : IDL.Text }),
  'isPremiumMember' : IDL.Bool,
  'points' : IDL.Nat,
  'musicUploads' : IDL.Vec(MusicUpload),
});
export const SearchEngine = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'apiUrl' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const DirectMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Timestamp,
  'receiver' : UserId,
});
export const Group = IDL.Record({
  'id' : GroupId,
  'members' : IDL.Vec(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
});
export const MediaAttachment = IDL.Record({
  'url' : IDL.Text,
  'contentType' : IDL.Text,
  'mediaType' : IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  }),
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'mediaAttachment' : IDL.Opt(MediaAttachment),
  'sender' : UserId,
  'groupId' : GroupId,
  'timestamp' : Timestamp,
});
export const TransactionType = IDL.Variant({
  'earn' : IDL.Null,
  'spend' : IDL.Null,
  'purchase' : IDL.Null,
});
export const PointsTransaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'userId' : UserId,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'amount' : IDL.Int,
});
export const FeedItem = IDL.Record({
  'status' : Status,
  'username' : IDL.Text,
  'userId' : UserId,
  'timestamp' : Timestamp,
});
export const SearchHistoryEntry = IDL.Record({
  'userId' : UserId,
  'searchTerm' : IDL.Text,
  'searchType' : IDL.Text,
  'timestamp' : Timestamp,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const DailyMysteryItemData = IDL.Record({
  'id' : IDL.Text,
  'userId' : UserId,
  'lastDailyItemClaim' : IDL.Opt(Timestamp),
  'newDailyItemResult' : IDL.Opt(MysteryItem),
  'dailyItemBoxOpened' : IDL.Bool,
});
export const SearchResult = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'userId' : UserId,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'profilePicture' : IDL.Record({ 'url' : IDL.Text, 'contentType' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateFreeTrial' : IDL.Func([], [], []),
  'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
  'addMysteryItem' : IDL.Func([MysteryItem], [], []),
  'addStoreItem' : IDL.Func([PointsStoreItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPointsEligibility' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'claimDailyItemsSecret' : IDL.Func([], [IDL.Opt(MysteryItem)], []),
  'claimDailyReward' : IDL.Func([], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [GroupId], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMysteryItem' : IDL.Func([IDL.Text], [], []),
  'deleteStoreItem' : IDL.Func([IDL.Text], [], []),
  'getAllMysteryItems' : IDL.Func([], [IDL.Vec(MysteryItem)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAvailableSearchEngines' : IDL.Func(
      [],
      [IDL.Vec(SearchEngine)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultSearchEngine' : IDL.Func([], [IDL.Text], ['query']),
  'getDirectMessagePartners' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getFriendsMusicUploads' : IDL.Func(
      [UserId],
      [IDL.Vec(MusicUpload)],
      ['query'],
    ),
  'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
  'getGroupMessages' : IDL.Func([GroupId], [IDL.Vec(GroupMessage)], ['query']),
  'getLastClaimedMysteryItem' : IDL.Func(
      [UserId],
      [IDL.Opt(MysteryItem)],
      ['query'],
    ),
  'getLastOnline' : IDL.Func([UserId], [Timestamp], ['query']),
  'getLastOnlineForMultipleUsers' : IDL.Func(
      [IDL.Vec(UserId)],
      [IDL.Vec(IDL.Tuple(UserId, Timestamp))],
      ['query'],
    ),
  'getPointsBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getPointsHistory' : IDL.Func([], [IDL.Vec(PointsTransaction)], ['query']),
  'getProfile' : IDL.Func([UserId], [UserProfile], ['query']),
  'getRecentStatuses' : IDL.Func([IDL.Nat], [IDL.Vec(FeedItem)], ['query']),
  'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistoryEntry)], ['query']),
  'getStoreItems' : IDL.Func([], [IDL.Vec(PointsStoreItem)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getUserMysteryItems' : IDL.Func(
      [UserId],
      [IDL.Vec(DailyMysteryItemData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMysteryItemClaimAvailable' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'purchasePoints' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'purchaseStoreItem' : IDL.Func([IDL.Text], [IDL.Text], []),
  'recordSearchHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendGroupMessage' : IDL.Func(
      [GroupId, IDL.Text, IDL.Opt(MediaAttachment)],
      [],
      [],
    ),
  'setDefaultSearchEngine' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'spendPoints' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLastOnline' : IDL.Func([], [], []),
  'updateMysteryItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Record({ 'url' : IDL.Text, 'contentType' : IDL.Text })],
      [],
      [],
    ),
  'updateStoreItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'upgradeToPremium' : IDL.Func([IDL.Nat], [], []),
  'uploadMusic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GroupId = IDL.Text;
  const UserId = IDL.Principal;
  const MysteryItemType = IDL.Variant({
    'message' : IDL.Null,
    'badge' : IDL.Null,
    'visual' : IDL.Null,
    'points' : IDL.Null,
  });
  const MysteryItem = IDL.Record({
    'id' : IDL.Text,
    'visualUrl' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rewardCooldown' : IDL.Opt(IDL.Nat),
    'itemType' : MysteryItemType,
    'pointsReward' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const PointsStoreItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Status = IDL.Text;
  const Badge = IDL.Record({
    'name' : IDL.Text,
    'typeId' : IDL.Nat,
    'description' : IDL.Text,
    'earnedAt' : Timestamp,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MusicUpload = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
    'uploadTime' : Timestamp,
    'uploadedBy' : UserId,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'status' : Status,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'badges' : IDL.Vec(Badge),
    'publishedAppsCount' : IDL.Nat,
    'premiumExpiresAt' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'rewardsClaimed' : IDL.Nat,
    'freeTrialStartTime' : IDL.Opt(Timestamp),
    'freeTrialExpiresAt' : IDL.Opt(Timestamp),
    'lastDailyRewardClaim' : IDL.Opt(Timestamp),
    'dailyLoginStreak' : IDL.Nat,
    'lastOnline' : Timestamp,
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'profilePicture' : IDL.Record({
      'url' : IDL.Text,
      'contentType' : IDL.Text,
    }),
    'isPremiumMember' : IDL.Bool,
    'points' : IDL.Nat,
    'musicUploads' : IDL.Vec(MusicUpload),
  });
  const SearchEngine = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'apiUrl' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const DirectMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Timestamp,
    'receiver' : UserId,
  });
  const Group = IDL.Record({
    'id' : GroupId,
    'members' : IDL.Vec(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
  });
  const MediaAttachment = IDL.Record({
    'url' : IDL.Text,
    'contentType' : IDL.Text,
    'mediaType' : IDL.Variant({
      'audio' : IDL.Null,
      'video' : IDL.Null,
      'image' : IDL.Null,
    }),
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'mediaAttachment' : IDL.Opt(MediaAttachment),
    'sender' : UserId,
    'groupId' : GroupId,
    'timestamp' : Timestamp,
  });
  const TransactionType = IDL.Variant({
    'earn' : IDL.Null,
    'spend' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const PointsTransaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'userId' : UserId,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'amount' : IDL.Int,
  });
  const FeedItem = IDL.Record({
    'status' : Status,
    'username' : IDL.Text,
    'userId' : UserId,
    'timestamp' : Timestamp,
  });
  const SearchHistoryEntry = IDL.Record({
    'userId' : UserId,
    'searchTerm' : IDL.Text,
    'searchType' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const DailyMysteryItemData = IDL.Record({
    'id' : IDL.Text,
    'userId' : UserId,
    'lastDailyItemClaim' : IDL.Opt(Timestamp),
    'newDailyItemResult' : IDL.Opt(MysteryItem),
    'dailyItemBoxOpened' : IDL.Bool,
  });
  const SearchResult = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'userId' : UserId,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'profilePicture' : IDL.Record({
      'url' : IDL.Text,
      'contentType' : IDL.Text,
    }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateFreeTrial' : IDL.Func([], [], []),
    'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
    'addMysteryItem' : IDL.Func([MysteryItem], [], []),
    'addStoreItem' : IDL.Func([PointsStoreItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPointsEligibility' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'claimDailyItemsSecret' : IDL.Func([], [IDL.Opt(MysteryItem)], []),
    'claimDailyReward' : IDL.Func([], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [GroupId], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMysteryItem' : IDL.Func([IDL.Text], [], []),
    'deleteStoreItem' : IDL.Func([IDL.Text], [], []),
    'getAllMysteryItems' : IDL.Func([], [IDL.Vec(MysteryItem)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAvailableSearchEngines' : IDL.Func(
        [],
        [IDL.Vec(SearchEngine)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultSearchEngine' : IDL.Func([], [IDL.Text], ['query']),
    'getDirectMessagePartners' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getFriendsMusicUploads' : IDL.Func(
        [UserId],
        [IDL.Vec(MusicUpload)],
        ['query'],
      ),
    'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
    'getGroupMessages' : IDL.Func(
        [GroupId],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getLastClaimedMysteryItem' : IDL.Func(
        [UserId],
        [IDL.Opt(MysteryItem)],
        ['query'],
      ),
    'getLastOnline' : IDL.Func([UserId], [Timestamp], ['query']),
    'getLastOnlineForMultipleUsers' : IDL.Func(
        [IDL.Vec(UserId)],
        [IDL.Vec(IDL.Tuple(UserId, Timestamp))],
        ['query'],
      ),
    'getPointsBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getPointsHistory' : IDL.Func([], [IDL.Vec(PointsTransaction)], ['query']),
    'getProfile' : IDL.Func([UserId], [UserProfile], ['query']),
    'getRecentStatuses' : IDL.Func([IDL.Nat], [IDL.Vec(FeedItem)], ['query']),
    'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistoryEntry)], ['query']),
    'getStoreItems' : IDL.Func([], [IDL.Vec(PointsStoreItem)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getUserMysteryItems' : IDL.Func(
        [UserId],
        [IDL.Vec(DailyMysteryItemData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMysteryItemClaimAvailable' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'purchasePoints' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'purchaseStoreItem' : IDL.Func([IDL.Text], [IDL.Text], []),
    'recordSearchHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendGroupMessage' : IDL.Func(
        [GroupId, IDL.Text, IDL.Opt(MediaAttachment)],
        [],
        [],
      ),
    'setDefaultSearchEngine' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'spendPoints' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLastOnline' : IDL.Func([], [], []),
    'updateMysteryItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Record({ 'url' : IDL.Text, 'contentType' : IDL.Text })],
        [],
        [],
      ),
    'updateStoreItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'upgradeToPremium' : IDL.Func([IDL.Nat], [], []),
    'uploadMusic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };