/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'name' : string,
  'typeId' : bigint,
  'description' : string,
  'earnedAt' : Timestamp,
}
export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : GroupId,
  'members' : Array<UserId>,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
}
export type GroupId = string;
export interface GroupMessage {
  'id' : string,
  'content' : string,
  'mediaAttachment' : [] | [MediaAttachment],
  'color' : MessageColor,
  'effect' : MessageEffect,
  'sender' : UserId,
  'groupId' : GroupId,
  'timestamp' : Timestamp,
}
export interface MediaAttachment {
  'url' : string,
  'contentType' : string,
  'mediaType' : { 'audio' : null } |
    { 'video' : null } |
    { 'image' : null },
}
export type MembershipTier = { 'pro' : null } |
  { 'free' : null } |
  { 'ultra' : null } |
  { 'ultimate' : null };
export type MessageColor = { 'normal' : null } |
  { 'blue' : null } |
  { 'cyan' : null } |
  { 'orange' : null } |
  { 'purple' : null } |
  { 'black' : null };
export type MessageEffect = { 'fiery' : null } |
  { 'none' : null } |
  { 'skull' : null } |
  { 'animated' : null } |
  { 'spooky' : null } |
  { 'devil' : null } |
  { 'dodge' : null };
export interface MusicUpload {
  'id' : string,
  'title' : string,
  'file' : ExternalBlob,
  'genre' : string,
  'artist' : string,
  'uploadTime' : Timestamp,
  'uploadedBy' : UserId,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Status = string;
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'status' : Status,
  'username' : string,
  'createdAt' : Timestamp,
  'badges' : Array<Badge>,
  'publishedAppsCount' : bigint,
  'premiumExpiresAt' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'rewardsClaimed' : bigint,
  'freeTrialStartTime' : [] | [Timestamp],
  'freeTrialExpiresAt' : [] | [Timestamp],
  'lastDailyRewardClaim' : [] | [Timestamp],
  'dailyLoginStreak' : bigint,
  'lastOnline' : Timestamp,
  'followers' : Array<UserId>,
  'following' : Array<UserId>,
  'profilePicture' : { 'url' : string, 'contentType' : string },
  'membershipTier' : MembershipTier,
  'isPremiumMember' : boolean,
  'points' : bigint,
  'musicUploads' : Array<MusicUpload>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupMember' : ActorMethod<[GroupId, UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGroup' : ActorMethod<[string, string], GroupId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroup' : ActorMethod<[GroupId], [] | [Group]>,
  'getGroupMessages' : ActorMethod<[GroupId], Array<GroupMessage>>,
  'getMembershipTier' : ActorMethod<[UserId], MembershipTier>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserGroups' : ActorMethod<[], Array<Group>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGroupMessage' : ActorMethod<
    [GroupId, string, [] | [MediaAttachment], MessageColor, MessageEffect],
    undefined
  >,
  'sendGroupMessageLegacy' : ActorMethod<
    [GroupId, string, [] | [MediaAttachment]],
    undefined
  >,
  'setMembershipTier' : ActorMethod<[UserId, MembershipTier], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];