/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GroupId = IDL.Text;
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Status = IDL.Text;
export const Timestamp = IDL.Int;
export const Badge = IDL.Record({
  'name' : IDL.Text,
  'typeId' : IDL.Nat,
  'description' : IDL.Text,
  'earnedAt' : Timestamp,
});
export const MembershipTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
  'ultra' : IDL.Null,
  'ultimate' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MusicUpload = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
  'uploadTime' : Timestamp,
  'uploadedBy' : UserId,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'status' : Status,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'badges' : IDL.Vec(Badge),
  'publishedAppsCount' : IDL.Nat,
  'premiumExpiresAt' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'rewardsClaimed' : IDL.Nat,
  'freeTrialStartTime' : IDL.Opt(Timestamp),
  'freeTrialExpiresAt' : IDL.Opt(Timestamp),
  'lastDailyRewardClaim' : IDL.Opt(Timestamp),
  'dailyLoginStreak' : IDL.Nat,
  'lastOnline' : Timestamp,
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'profilePicture' : IDL.Record({ 'url' : IDL.Text, 'contentType' : IDL.Text }),
  'membershipTier' : MembershipTier,
  'isPremiumMember' : IDL.Bool,
  'points' : IDL.Nat,
  'musicUploads' : IDL.Vec(MusicUpload),
});
export const Group = IDL.Record({
  'id' : GroupId,
  'members' : IDL.Vec(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
});
export const MediaAttachment = IDL.Record({
  'url' : IDL.Text,
  'contentType' : IDL.Text,
  'mediaType' : IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  }),
});
export const MessageColor = IDL.Variant({
  'normal' : IDL.Null,
  'blue' : IDL.Null,
  'cyan' : IDL.Null,
  'orange' : IDL.Null,
  'purple' : IDL.Null,
  'black' : IDL.Null,
});
export const MessageEffect = IDL.Variant({
  'fiery' : IDL.Null,
  'none' : IDL.Null,
  'skull' : IDL.Null,
  'animated' : IDL.Null,
  'spooky' : IDL.Null,
  'devil' : IDL.Null,
  'dodge' : IDL.Null,
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'mediaAttachment' : IDL.Opt(MediaAttachment),
  'color' : MessageColor,
  'effect' : MessageEffect,
  'sender' : UserId,
  'groupId' : GroupId,
  'timestamp' : Timestamp,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [GroupId], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
  'getGroupMessages' : IDL.Func([GroupId], [IDL.Vec(GroupMessage)], ['query']),
  'getMembershipTier' : IDL.Func([UserId], [MembershipTier], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGroupMessage' : IDL.Func(
      [
        GroupId,
        IDL.Text,
        IDL.Opt(MediaAttachment),
        MessageColor,
        MessageEffect,
      ],
      [],
      [],
    ),
  'sendGroupMessageLegacy' : IDL.Func(
      [GroupId, IDL.Text, IDL.Opt(MediaAttachment)],
      [],
      [],
    ),
  'setMembershipTier' : IDL.Func([UserId, MembershipTier], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GroupId = IDL.Text;
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Status = IDL.Text;
  const Timestamp = IDL.Int;
  const Badge = IDL.Record({
    'name' : IDL.Text,
    'typeId' : IDL.Nat,
    'description' : IDL.Text,
    'earnedAt' : Timestamp,
  });
  const MembershipTier = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
    'ultra' : IDL.Null,
    'ultimate' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MusicUpload = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
    'uploadTime' : Timestamp,
    'uploadedBy' : UserId,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'status' : Status,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'badges' : IDL.Vec(Badge),
    'publishedAppsCount' : IDL.Nat,
    'premiumExpiresAt' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'rewardsClaimed' : IDL.Nat,
    'freeTrialStartTime' : IDL.Opt(Timestamp),
    'freeTrialExpiresAt' : IDL.Opt(Timestamp),
    'lastDailyRewardClaim' : IDL.Opt(Timestamp),
    'dailyLoginStreak' : IDL.Nat,
    'lastOnline' : Timestamp,
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'profilePicture' : IDL.Record({
      'url' : IDL.Text,
      'contentType' : IDL.Text,
    }),
    'membershipTier' : MembershipTier,
    'isPremiumMember' : IDL.Bool,
    'points' : IDL.Nat,
    'musicUploads' : IDL.Vec(MusicUpload),
  });
  const Group = IDL.Record({
    'id' : GroupId,
    'members' : IDL.Vec(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
  });
  const MediaAttachment = IDL.Record({
    'url' : IDL.Text,
    'contentType' : IDL.Text,
    'mediaType' : IDL.Variant({
      'audio' : IDL.Null,
      'video' : IDL.Null,
      'image' : IDL.Null,
    }),
  });
  const MessageColor = IDL.Variant({
    'normal' : IDL.Null,
    'blue' : IDL.Null,
    'cyan' : IDL.Null,
    'orange' : IDL.Null,
    'purple' : IDL.Null,
    'black' : IDL.Null,
  });
  const MessageEffect = IDL.Variant({
    'fiery' : IDL.Null,
    'none' : IDL.Null,
    'skull' : IDL.Null,
    'animated' : IDL.Null,
    'spooky' : IDL.Null,
    'devil' : IDL.Null,
    'dodge' : IDL.Null,
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'mediaAttachment' : IDL.Opt(MediaAttachment),
    'color' : MessageColor,
    'effect' : MessageEffect,
    'sender' : UserId,
    'groupId' : GroupId,
    'timestamp' : Timestamp,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [GroupId], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
    'getGroupMessages' : IDL.Func(
        [GroupId],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getMembershipTier' : IDL.Func([UserId], [MembershipTier], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGroupMessage' : IDL.Func(
        [
          GroupId,
          IDL.Text,
          IDL.Opt(MediaAttachment),
          MessageColor,
          MessageEffect,
        ],
        [],
        [],
      ),
    'sendGroupMessageLegacy' : IDL.Func(
        [GroupId, IDL.Text, IDL.Opt(MediaAttachment)],
        [],
        [],
      ),
    'setMembershipTier' : IDL.Func([UserId, MembershipTier], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };