/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchResult {
    bio: string;
    username: string;
    userId: UserId;
    followerCount: bigint;
    followingCount: bigint;
    profilePicture: {
        url: string;
        contentType: string;
    };
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MusicUpload {
    id: string;
    title: string;
    file: ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: Timestamp;
    uploadedBy: UserId;
}
export interface PointsStoreItem {
    id: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    price: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DailyMysteryItemData {
    id: string;
    userId: UserId;
    lastDailyItemClaim?: Timestamp;
    newDailyItemResult?: MysteryItem;
    dailyItemBoxOpened: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PointsTransaction {
    id: string;
    transactionType: TransactionType;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    amount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface Badge {
    name: string;
    typeId: bigint;
    description: string;
    earnedAt: Timestamp;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type Points = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FeedItem {
    status: Status;
    username: string;
    userId: UserId;
    timestamp: Timestamp;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type Status = string;
export interface MysteryItem {
    id: string;
    visualUrl?: string;
    name: string;
    description: string;
    rewardCooldown?: bigint;
    itemType: MysteryItemType;
    pointsReward?: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    bio: string;
    status: Status;
    username: string;
    createdAt: Timestamp;
    badges: Array<Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt?: Timestamp;
    updatedAt: Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime?: Timestamp;
    freeTrialExpiresAt?: Timestamp;
    lastDailyRewardClaim?: Timestamp;
    dailyLoginStreak: bigint;
    lastOnline: Timestamp;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    isPremiumMember: boolean;
    points: Points;
    musicUploads: Array<MusicUpload>;
}
export enum MysteryItemType {
    message = "message",
    badge = "badge",
    visual = "visual",
    points = "points"
}
export enum TransactionType {
    earn = "earn",
    spend = "spend",
    purchase = "purchase"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateFreeTrial(): Promise<void>;
    addMysteryItem(mysteryItem: MysteryItem): Promise<void>;
    addStoreItem(item: PointsStoreItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkPointsEligibility(requiredPoints: bigint): Promise<string>;
    claimDailyItemsSecret(): Promise<MysteryItem | null>;
    claimDailyReward(): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createProfile(username: string, bio: string): Promise<void>;
    deleteMysteryItem(id: string): Promise<void>;
    deleteStoreItem(id: string): Promise<void>;
    getAllMysteryItems(): Promise<Array<MysteryItem>>;
    getAllProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFriendsMusicUploads(userId: UserId): Promise<Array<MusicUpload>>;
    getLastClaimedMysteryItem(userId: UserId): Promise<MysteryItem | null>;
    getLastOnline(userId: UserId): Promise<Timestamp>;
    getLastOnlineForMultipleUsers(userIds: Array<UserId>): Promise<Array<[UserId, Timestamp]>>;
    getPointsBalance(): Promise<bigint>;
    getPointsHistory(): Promise<Array<PointsTransaction>>;
    getProfile(userId: UserId): Promise<UserProfile>;
    getRecentStatuses(limit: bigint): Promise<Array<FeedItem>>;
    getStoreItems(): Promise<Array<PointsStoreItem>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserMysteryItems(userId: UserId): Promise<Array<DailyMysteryItemData>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isMysteryItemClaimAvailable(userId: UserId): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    purchasePoints(pointsToBuy: bigint): Promise<string>;
    purchaseStoreItem(storeItemId: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProfiles(searchTerm: string): Promise<Array<SearchResult>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    spendPoints(amount: bigint): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateLastOnline(): Promise<void>;
    updateMysteryItem(id: string, name: string, description: string, pointsReward: bigint | null, visualUrl: string | null, rewardCooldown: bigint | null): Promise<void>;
    updateProfile(bio: string, profilePicture: {
        url: string;
        contentType: string;
    }): Promise<void>;
    updateStoreItem(id: string, name: string, description: string, price: bigint): Promise<void>;
    upgradeToPremium(months: bigint): Promise<void>;
    uploadMusic(id: string, title: string, artist: string, genre: string, file: ExternalBlob): Promise<void>;
}
import type { Badge as _Badge, DailyMysteryItemData as _DailyMysteryItemData, ExternalBlob as _ExternalBlob, MusicUpload as _MusicUpload, MysteryItem as _MysteryItem, MysteryItemType as _MysteryItemType, Points as _Points, PointsTransaction as _PointsTransaction, Status as _Status, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, TransactionType as _TransactionType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateFreeTrial(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateFreeTrial();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateFreeTrial();
            return result;
        }
    }
    async addMysteryItem(arg0: MysteryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMysteryItem(to_candid_MysteryItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMysteryItem(to_candid_MysteryItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStoreItem(arg0: PointsStoreItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStoreItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStoreItem(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkPointsEligibility(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPointsEligibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPointsEligibility(arg0);
            return result;
        }
    }
    async claimDailyItemsSecret(): Promise<MysteryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyItemsSecret();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyItemsSecret();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimDailyReward(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyReward();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyReward();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1);
            return result;
        }
    }
    async deleteMysteryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMysteryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMysteryItem(arg0);
            return result;
        }
    }
    async deleteStoreItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStoreItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStoreItem(arg0);
            return result;
        }
    }
    async getAllMysteryItems(): Promise<Array<MysteryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMysteryItems();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMysteryItems();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendsMusicUploads(arg0: UserId): Promise<Array<MusicUpload>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsMusicUploads(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsMusicUploads(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastClaimedMysteryItem(arg0: UserId): Promise<MysteryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastClaimedMysteryItem(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastClaimedMysteryItem(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastOnline(arg0: UserId): Promise<Timestamp> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastOnline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastOnline(arg0);
            return result;
        }
    }
    async getLastOnlineForMultipleUsers(arg0: Array<UserId>): Promise<Array<[UserId, Timestamp]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastOnlineForMultipleUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastOnlineForMultipleUsers(arg0);
            return result;
        }
    }
    async getPointsBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointsBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointsBalance();
            return result;
        }
    }
    async getPointsHistory(): Promise<Array<PointsTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointsHistory();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointsHistory();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_UserProfile_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_UserProfile_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentStatuses(arg0: bigint): Promise<Array<FeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentStatuses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentStatuses(arg0);
            return result;
        }
    }
    async getStoreItems(): Promise<Array<PointsStoreItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreItems();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMysteryItems(arg0: UserId): Promise<Array<DailyMysteryItemData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMysteryItems(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMysteryItems(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isMysteryItemClaimAvailable(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMysteryItemClaimAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMysteryItemClaimAvailable(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async purchasePoints(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePoints(arg0);
            return result;
        }
    }
    async purchaseStoreItem(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseStoreItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseStoreItem(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProfiles(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProfiles(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async spendPoints(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.spendPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spendPoints(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateLastOnline(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastOnline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastOnline();
            return result;
        }
    }
    async updateMysteryItem(arg0: string, arg1: string, arg2: string, arg3: bigint | null, arg4: string | null, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMysteryItem(arg0, arg1, arg2, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMysteryItem(arg0, arg1, arg2, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: {
        url: string;
        contentType: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return result;
        }
    }
    async updateStoreItem(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async upgradeToPremium(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPremium(arg0);
            return result;
        }
    }
    async uploadMusic(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMusic(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMusic(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_DailyMysteryItemData_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyMysteryItemData): DailyMysteryItemData {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MusicUpload_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MusicUpload): Promise<MusicUpload> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MysteryItemType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MysteryItemType): MysteryItemType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_MysteryItem_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MysteryItem): MysteryItem {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PointsTransaction_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PointsTransaction): PointsTransaction {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MysteryItem]): MysteryItem | null {
    return value.length === 0 ? null : from_candid_MysteryItem_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    visualUrl: [] | [string];
    name: string;
    description: string;
    rewardCooldown: [] | [bigint];
    itemType: _MysteryItemType;
    pointsReward: [] | [bigint];
}): {
    id: string;
    visualUrl?: string;
    name: string;
    description: string;
    rewardCooldown?: bigint;
    itemType: MysteryItemType;
    pointsReward?: bigint;
} {
    return {
        id: value.id,
        visualUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.visualUrl)),
        name: value.name,
        description: value.description,
        rewardCooldown: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rewardCooldown)),
        itemType: from_candid_MysteryItemType_n18(_uploadFile, _downloadFile, value.itemType),
        pointsReward: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pointsReward))
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    status: _Status;
    username: string;
    createdAt: _Timestamp;
    badges: Array<_Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt: [] | [_Timestamp];
    updatedAt: _Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime: [] | [_Timestamp];
    freeTrialExpiresAt: [] | [_Timestamp];
    lastDailyRewardClaim: [] | [_Timestamp];
    dailyLoginStreak: bigint;
    lastOnline: _Timestamp;
    followers: Array<_UserId>;
    following: Array<_UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    isPremiumMember: boolean;
    points: _Points;
    musicUploads: Array<_MusicUpload>;
}): Promise<{
    bio: string;
    status: Status;
    username: string;
    createdAt: Timestamp;
    badges: Array<Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt?: Timestamp;
    updatedAt: Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime?: Timestamp;
    freeTrialExpiresAt?: Timestamp;
    lastDailyRewardClaim?: Timestamp;
    dailyLoginStreak: bigint;
    lastOnline: Timestamp;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    isPremiumMember: boolean;
    points: Points;
    musicUploads: Array<MusicUpload>;
}> {
    return {
        bio: value.bio,
        status: value.status,
        username: value.username,
        createdAt: value.createdAt,
        badges: value.badges,
        publishedAppsCount: value.publishedAppsCount,
        premiumExpiresAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.premiumExpiresAt)),
        updatedAt: value.updatedAt,
        rewardsClaimed: value.rewardsClaimed,
        freeTrialStartTime: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.freeTrialStartTime)),
        freeTrialExpiresAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.freeTrialExpiresAt)),
        lastDailyRewardClaim: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.lastDailyRewardClaim)),
        dailyLoginStreak: value.dailyLoginStreak,
        lastOnline: value.lastOnline,
        followers: value.followers,
        following: value.following,
        profilePicture: value.profilePicture,
        isPremiumMember: value.isPremiumMember,
        points: value.points,
        musicUploads: await from_candid_vec_n25(_uploadFile, _downloadFile, value.musicUploads)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    file: _ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: _Timestamp;
    uploadedBy: _UserId;
}): Promise<{
    id: string;
    title: string;
    file: ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: Timestamp;
    uploadedBy: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.file),
        genre: value.genre,
        artist: value.artist,
        uploadTime: value.uploadTime,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: _TransactionType;
    userId: _UserId;
    description: string;
    timestamp: _Timestamp;
    amount: bigint;
}): {
    id: string;
    transactionType: TransactionType;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n35(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userId: _UserId;
    lastDailyItemClaim: [] | [_Timestamp];
    newDailyItemResult: [] | [_MysteryItem];
    dailyItemBoxOpened: boolean;
}): {
    id: string;
    userId: UserId;
    lastDailyItemClaim?: Timestamp;
    newDailyItemResult?: MysteryItem;
    dailyItemBoxOpened: boolean;
} {
    return {
        id: value.id,
        userId: value.userId,
        lastDailyItemClaim: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.lastDailyItemClaim)),
        newDailyItemResult: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.newDailyItemResult)),
        dailyItemBoxOpened: value.dailyItemBoxOpened
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: null;
} | {
    badge: null;
} | {
    visual: null;
} | {
    points: null;
}): MysteryItemType {
    return "message" in value ? MysteryItemType.message : "badge" in value ? MysteryItemType.badge : "visual" in value ? MysteryItemType.visual : "points" in value ? MysteryItemType.points : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    earn: null;
} | {
    spend: null;
} | {
    purchase: null;
}): TransactionType {
    return "earn" in value ? TransactionType.earn : "spend" in value ? TransactionType.spend : "purchase" in value ? TransactionType.purchase : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n39(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MysteryItem>): Array<MysteryItem> {
    return value.map((x)=>from_candid_MysteryItem_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MusicUpload>): Promise<Array<MusicUpload>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MusicUpload_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PointsTransaction>): Array<PointsTransaction> {
    return value.map((x)=>from_candid_PointsTransaction_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyMysteryItemData>): Array<DailyMysteryItemData> {
    return value.map((x)=>from_candid_DailyMysteryItemData_n41(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MusicUpload_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicUpload): Promise<_MusicUpload> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_MysteryItemType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MysteryItemType): _MysteryItemType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MysteryItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MysteryItem): _MysteryItem {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    status: Status;
    username: string;
    createdAt: Timestamp;
    badges: Array<Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt?: Timestamp;
    updatedAt: Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime?: Timestamp;
    freeTrialExpiresAt?: Timestamp;
    lastDailyRewardClaim?: Timestamp;
    dailyLoginStreak: bigint;
    lastOnline: Timestamp;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    isPremiumMember: boolean;
    points: Points;
    musicUploads: Array<MusicUpload>;
}): Promise<{
    bio: string;
    status: _Status;
    username: string;
    createdAt: _Timestamp;
    badges: Array<_Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt: [] | [_Timestamp];
    updatedAt: _Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime: [] | [_Timestamp];
    freeTrialExpiresAt: [] | [_Timestamp];
    lastDailyRewardClaim: [] | [_Timestamp];
    dailyLoginStreak: bigint;
    lastOnline: _Timestamp;
    followers: Array<_UserId>;
    following: Array<_UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    isPremiumMember: boolean;
    points: _Points;
    musicUploads: Array<_MusicUpload>;
}> {
    return {
        bio: value.bio,
        status: value.status,
        username: value.username,
        createdAt: value.createdAt,
        badges: value.badges,
        publishedAppsCount: value.publishedAppsCount,
        premiumExpiresAt: value.premiumExpiresAt ? candid_some(value.premiumExpiresAt) : candid_none(),
        updatedAt: value.updatedAt,
        rewardsClaimed: value.rewardsClaimed,
        freeTrialStartTime: value.freeTrialStartTime ? candid_some(value.freeTrialStartTime) : candid_none(),
        freeTrialExpiresAt: value.freeTrialExpiresAt ? candid_some(value.freeTrialExpiresAt) : candid_none(),
        lastDailyRewardClaim: value.lastDailyRewardClaim ? candid_some(value.lastDailyRewardClaim) : candid_none(),
        dailyLoginStreak: value.dailyLoginStreak,
        lastOnline: value.lastOnline,
        followers: value.followers,
        following: value.following,
        profilePicture: value.profilePicture,
        isPremiumMember: value.isPremiumMember,
        points: value.points,
        musicUploads: await to_candid_vec_n45(_uploadFile, _downloadFile, value.musicUploads)
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    file: ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: Timestamp;
    uploadedBy: UserId;
}): Promise<{
    id: string;
    title: string;
    file: _ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: _Timestamp;
    uploadedBy: _UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.file),
        genre: value.genre,
        artist: value.artist,
        uploadTime: value.uploadTime,
        uploadedBy: value.uploadedBy
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    visualUrl?: string;
    name: string;
    description: string;
    rewardCooldown?: bigint;
    itemType: MysteryItemType;
    pointsReward?: bigint;
}): {
    id: string;
    visualUrl: [] | [string];
    name: string;
    description: string;
    rewardCooldown: [] | [bigint];
    itemType: _MysteryItemType;
    pointsReward: [] | [bigint];
} {
    return {
        id: value.id,
        visualUrl: value.visualUrl ? candid_some(value.visualUrl) : candid_none(),
        name: value.name,
        description: value.description,
        rewardCooldown: value.rewardCooldown ? candid_some(value.rewardCooldown) : candid_none(),
        itemType: to_candid_MysteryItemType_n10(_uploadFile, _downloadFile, value.itemType),
        pointsReward: value.pointsReward ? candid_some(value.pointsReward) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MysteryItemType): {
    message: null;
} | {
    badge: null;
} | {
    visual: null;
} | {
    points: null;
} {
    return value == MysteryItemType.message ? {
        message: null
    } : value == MysteryItemType.badge ? {
        badge: null
    } : value == MysteryItemType.visual ? {
        visual: null
    } : value == MysteryItemType.points ? {
        points: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MusicUpload>): Promise<Array<_MusicUpload>> {
    return await Promise.all(value.map(async (x)=>await to_candid_MusicUpload_n46(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
