/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MusicUpload {
    id: string;
    title: string;
    file: ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: Timestamp;
    uploadedBy: UserId;
}
export interface GroupMessage {
    id: string;
    content: string;
    mediaAttachment?: MediaAttachment;
    color: MessageColor;
    effect: MessageEffect;
    sender: UserId;
    groupId: GroupId;
    timestamp: Timestamp;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Group {
    id: GroupId;
    members: Array<UserId>;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MediaAttachment {
    url: string;
    contentType: string;
    mediaType: Variant_audio_video_image;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type GroupId = string;
export type UserId = Principal;
export interface Badge {
    name: string;
    typeId: bigint;
    description: string;
    earnedAt: Timestamp;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type Status = string;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    bio: string;
    status: Status;
    username: string;
    createdAt: Timestamp;
    badges: Array<Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt?: Timestamp;
    updatedAt: Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime?: Timestamp;
    freeTrialExpiresAt?: Timestamp;
    lastDailyRewardClaim?: Timestamp;
    dailyLoginStreak: bigint;
    lastOnline: Timestamp;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    membershipTier: MembershipTier;
    isPremiumMember: boolean;
    points: bigint;
    musicUploads: Array<MusicUpload>;
}
export enum MembershipTier {
    pro = "pro",
    free = "free",
    ultra = "ultra",
    ultimate = "ultimate"
}
export enum MessageColor {
    normal = "normal",
    blue = "blue",
    cyan = "cyan",
    orange = "orange",
    purple = "purple",
    black = "black"
}
export enum MessageEffect {
    fiery = "fiery",
    none = "none",
    skull = "skull",
    animated = "animated",
    spooky = "spooky",
    devil = "devil",
    dodge = "dodge"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_audio_video_image {
    audio = "audio",
    video = "video",
    image = "image"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGroupMember(groupId: GroupId, userId: UserId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGroup(name: string, description: string): Promise<GroupId>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGroup(groupId: GroupId): Promise<Group | null>;
    getGroupMessages(groupId: GroupId): Promise<Array<GroupMessage>>;
    getMembershipTier(userId: UserId): Promise<MembershipTier>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserGroups(): Promise<Array<Group>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendGroupMessage(groupId: GroupId, content: string, mediaAttachment: MediaAttachment | null, color: MessageColor, effect: MessageEffect): Promise<void>;
    sendGroupMessageLegacy(groupId: GroupId, content: string, mediaAttachment: MediaAttachment | null): Promise<void>;
    setMembershipTier(userId: UserId, tier: MembershipTier): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Badge as _Badge, ExternalBlob as _ExternalBlob, Group as _Group, GroupId as _GroupId, GroupMessage as _GroupMessage, MediaAttachment as _MediaAttachment, MembershipTier as _MembershipTier, MessageColor as _MessageColor, MessageEffect as _MessageEffect, MusicUpload as _MusicUpload, Status as _Status, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGroupMember(arg0: GroupId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string): Promise<GroupId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroup(arg0: GroupId): Promise<Group | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMessages(arg0: GroupId): Promise<Array<GroupMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessages(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessages(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipTier(arg0: UserId): Promise<MembershipTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipTier(arg0);
                return from_candid_MembershipTier_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipTier(arg0);
            return from_candid_MembershipTier_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGroups();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendGroupMessage(arg0: GroupId, arg1: string, arg2: MediaAttachment | null, arg3: MessageColor, arg4: MessageEffect): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGroupMessage(arg0, arg1, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2), to_candid_MessageColor_n50(this._uploadFile, this._downloadFile, arg3), to_candid_MessageEffect_n52(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGroupMessage(arg0, arg1, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2), to_candid_MessageColor_n50(this._uploadFile, this._downloadFile, arg3), to_candid_MessageEffect_n52(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async sendGroupMessageLegacy(arg0: GroupId, arg1: string, arg2: MediaAttachment | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGroupMessageLegacy(arg0, arg1, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGroupMessageLegacy(arg0, arg1, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setMembershipTier(arg0: UserId, arg1: MembershipTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMembershipTier(arg0, to_candid_MembershipTier_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMembershipTier(arg0, to_candid_MembershipTier_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GroupMessage_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupMessage): GroupMessage {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MediaAttachment_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaAttachment): MediaAttachment {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipTier_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipTier): MembershipTier {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MessageColor_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageColor): MessageColor {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_MessageEffect_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageEffect): MessageEffect {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_MusicUpload_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MusicUpload): Promise<MusicUpload> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Group]): Group | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaAttachment]): MediaAttachment | null {
    return value.length === 0 ? null : from_candid_MediaAttachment_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    status: _Status;
    username: string;
    createdAt: _Timestamp;
    badges: Array<_Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt: [] | [_Timestamp];
    updatedAt: _Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime: [] | [_Timestamp];
    freeTrialExpiresAt: [] | [_Timestamp];
    lastDailyRewardClaim: [] | [_Timestamp];
    dailyLoginStreak: bigint;
    lastOnline: _Timestamp;
    followers: Array<_UserId>;
    following: Array<_UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    membershipTier: _MembershipTier;
    isPremiumMember: boolean;
    points: bigint;
    musicUploads: Array<_MusicUpload>;
}): Promise<{
    bio: string;
    status: Status;
    username: string;
    createdAt: Timestamp;
    badges: Array<Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt?: Timestamp;
    updatedAt: Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime?: Timestamp;
    freeTrialExpiresAt?: Timestamp;
    lastDailyRewardClaim?: Timestamp;
    dailyLoginStreak: bigint;
    lastOnline: Timestamp;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    membershipTier: MembershipTier;
    isPremiumMember: boolean;
    points: bigint;
    musicUploads: Array<MusicUpload>;
}> {
    return {
        bio: value.bio,
        status: value.status,
        username: value.username,
        createdAt: value.createdAt,
        badges: value.badges,
        publishedAppsCount: value.publishedAppsCount,
        premiumExpiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.premiumExpiresAt)),
        updatedAt: value.updatedAt,
        rewardsClaimed: value.rewardsClaimed,
        freeTrialStartTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.freeTrialStartTime)),
        freeTrialExpiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.freeTrialExpiresAt)),
        lastDailyRewardClaim: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastDailyRewardClaim)),
        dailyLoginStreak: value.dailyLoginStreak,
        lastOnline: value.lastOnline,
        followers: value.followers,
        following: value.following,
        profilePicture: value.profilePicture,
        membershipTier: from_candid_MembershipTier_n14(_uploadFile, _downloadFile, value.membershipTier),
        isPremiumMember: value.isPremiumMember,
        points: value.points,
        musicUploads: await from_candid_vec_n16(_uploadFile, _downloadFile, value.musicUploads)
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    file: _ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: _Timestamp;
    uploadedBy: _UserId;
}): Promise<{
    id: string;
    title: string;
    file: ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: Timestamp;
    uploadedBy: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.file),
        genre: value.genre,
        artist: value.artist,
        uploadTime: value.uploadTime,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    mediaAttachment: [] | [_MediaAttachment];
    color: _MessageColor;
    effect: _MessageEffect;
    sender: _UserId;
    groupId: _GroupId;
    timestamp: _Timestamp;
}): {
    id: string;
    content: string;
    mediaAttachment?: MediaAttachment;
    color: MessageColor;
    effect: MessageEffect;
    sender: UserId;
    groupId: GroupId;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        mediaAttachment: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.mediaAttachment)),
        color: from_candid_MessageColor_n30(_uploadFile, _downloadFile, value.color),
        effect: from_candid_MessageEffect_n32(_uploadFile, _downloadFile, value.effect),
        sender: value.sender,
        groupId: value.groupId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    contentType: string;
    mediaType: {
        audio: null;
    } | {
        video: null;
    } | {
        image: null;
    };
}): {
    url: string;
    contentType: string;
    mediaType: Variant_audio_video_image;
} {
    return {
        url: value.url,
        contentType: value.contentType,
        mediaType: from_candid_variant_n29(_uploadFile, _downloadFile, value.mediaType)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    free: null;
} | {
    ultra: null;
} | {
    ultimate: null;
}): MembershipTier {
    return "pro" in value ? MembershipTier.pro : "free" in value ? MembershipTier.free : "ultra" in value ? MembershipTier.ultra : "ultimate" in value ? MembershipTier.ultimate : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    video: null;
} | {
    image: null;
}): Variant_audio_video_image {
    return "audio" in value ? Variant_audio_video_image.audio : "video" in value ? Variant_audio_video_image.video : "image" in value ? Variant_audio_video_image.image : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    blue: null;
} | {
    cyan: null;
} | {
    orange: null;
} | {
    purple: null;
} | {
    black: null;
}): MessageColor {
    return "normal" in value ? MessageColor.normal : "blue" in value ? MessageColor.blue : "cyan" in value ? MessageColor.cyan : "orange" in value ? MessageColor.orange : "purple" in value ? MessageColor.purple : "black" in value ? MessageColor.black : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fiery: null;
} | {
    none: null;
} | {
    skull: null;
} | {
    animated: null;
} | {
    spooky: null;
} | {
    devil: null;
} | {
    dodge: null;
}): MessageEffect {
    return "fiery" in value ? MessageEffect.fiery : "none" in value ? MessageEffect.none : "skull" in value ? MessageEffect.skull : "animated" in value ? MessageEffect.animated : "spooky" in value ? MessageEffect.spooky : "devil" in value ? MessageEffect.devil : "dodge" in value ? MessageEffect.dodge : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n36(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MusicUpload>): Promise<Array<MusicUpload>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MusicUpload_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupMessage>): Array<GroupMessage> {
    return value.map((x)=>from_candid_GroupMessage_n24(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MediaAttachment_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaAttachment): _MediaAttachment {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipTier_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): _MembershipTier {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_MessageColor_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageColor): _MessageColor {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_MessageEffect_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageEffect): _MessageEffect {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_MusicUpload_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicUpload): Promise<_MusicUpload> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaAttachment | null): [] | [_MediaAttachment] {
    return value === null ? candid_none() : candid_some(to_candid_MediaAttachment_n47(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    status: Status;
    username: string;
    createdAt: Timestamp;
    badges: Array<Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt?: Timestamp;
    updatedAt: Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime?: Timestamp;
    freeTrialExpiresAt?: Timestamp;
    lastDailyRewardClaim?: Timestamp;
    dailyLoginStreak: bigint;
    lastOnline: Timestamp;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    membershipTier: MembershipTier;
    isPremiumMember: boolean;
    points: bigint;
    musicUploads: Array<MusicUpload>;
}): Promise<{
    bio: string;
    status: _Status;
    username: string;
    createdAt: _Timestamp;
    badges: Array<_Badge>;
    publishedAppsCount: bigint;
    premiumExpiresAt: [] | [_Timestamp];
    updatedAt: _Timestamp;
    rewardsClaimed: bigint;
    freeTrialStartTime: [] | [_Timestamp];
    freeTrialExpiresAt: [] | [_Timestamp];
    lastDailyRewardClaim: [] | [_Timestamp];
    dailyLoginStreak: bigint;
    lastOnline: _Timestamp;
    followers: Array<_UserId>;
    following: Array<_UserId>;
    profilePicture: {
        url: string;
        contentType: string;
    };
    membershipTier: _MembershipTier;
    isPremiumMember: boolean;
    points: bigint;
    musicUploads: Array<_MusicUpload>;
}> {
    return {
        bio: value.bio,
        status: value.status,
        username: value.username,
        createdAt: value.createdAt,
        badges: value.badges,
        publishedAppsCount: value.publishedAppsCount,
        premiumExpiresAt: value.premiumExpiresAt ? candid_some(value.premiumExpiresAt) : candid_none(),
        updatedAt: value.updatedAt,
        rewardsClaimed: value.rewardsClaimed,
        freeTrialStartTime: value.freeTrialStartTime ? candid_some(value.freeTrialStartTime) : candid_none(),
        freeTrialExpiresAt: value.freeTrialExpiresAt ? candid_some(value.freeTrialExpiresAt) : candid_none(),
        lastDailyRewardClaim: value.lastDailyRewardClaim ? candid_some(value.lastDailyRewardClaim) : candid_none(),
        dailyLoginStreak: value.dailyLoginStreak,
        lastOnline: value.lastOnline,
        followers: value.followers,
        following: value.following,
        profilePicture: value.profilePicture,
        membershipTier: to_candid_MembershipTier_n40(_uploadFile, _downloadFile, value.membershipTier),
        isPremiumMember: value.isPremiumMember,
        points: value.points,
        musicUploads: await to_candid_vec_n42(_uploadFile, _downloadFile, value.musicUploads)
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    file: ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: Timestamp;
    uploadedBy: UserId;
}): Promise<{
    id: string;
    title: string;
    file: _ExternalBlob;
    genre: string;
    artist: string;
    uploadTime: _Timestamp;
    uploadedBy: _UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.file),
        genre: value.genre,
        artist: value.artist,
        uploadTime: value.uploadTime,
        uploadedBy: value.uploadedBy
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    contentType: string;
    mediaType: Variant_audio_video_image;
}): {
    url: string;
    contentType: string;
    mediaType: {
        audio: null;
    } | {
        video: null;
    } | {
        image: null;
    };
} {
    return {
        url: value.url,
        contentType: value.contentType,
        mediaType: to_candid_variant_n49(_uploadFile, _downloadFile, value.mediaType)
    };
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): {
    pro: null;
} | {
    free: null;
} | {
    ultra: null;
} | {
    ultimate: null;
} {
    return value == MembershipTier.pro ? {
        pro: null
    } : value == MembershipTier.free ? {
        free: null
    } : value == MembershipTier.ultra ? {
        ultra: null
    } : value == MembershipTier.ultimate ? {
        ultimate: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_audio_video_image): {
    audio: null;
} | {
    video: null;
} | {
    image: null;
} {
    return value == Variant_audio_video_image.audio ? {
        audio: null
    } : value == Variant_audio_video_image.video ? {
        video: null
    } : value == Variant_audio_video_image.image ? {
        image: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageColor): {
    normal: null;
} | {
    blue: null;
} | {
    cyan: null;
} | {
    orange: null;
} | {
    purple: null;
} | {
    black: null;
} {
    return value == MessageColor.normal ? {
        normal: null
    } : value == MessageColor.blue ? {
        blue: null
    } : value == MessageColor.cyan ? {
        cyan: null
    } : value == MessageColor.orange ? {
        orange: null
    } : value == MessageColor.purple ? {
        purple: null
    } : value == MessageColor.black ? {
        black: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageEffect): {
    fiery: null;
} | {
    none: null;
} | {
    skull: null;
} | {
    animated: null;
} | {
    spooky: null;
} | {
    devil: null;
} | {
    dodge: null;
} {
    return value == MessageEffect.fiery ? {
        fiery: null
    } : value == MessageEffect.none ? {
        none: null
    } : value == MessageEffect.skull ? {
        skull: null
    } : value == MessageEffect.animated ? {
        animated: null
    } : value == MessageEffect.spooky ? {
        spooky: null
    } : value == MessageEffect.devil ? {
        devil: null
    } : value == MessageEffect.dodge ? {
        dodge: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MusicUpload>): Promise<Array<_MusicUpload>> {
    return await Promise.all(value.map(async (x)=>await to_candid_MusicUpload_n43(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
